// Additional period models. Values and risk factors are game balance data.
NG.catalog.push(
  ...[
    {
      id: "skyline",
      name: "Nissan Skyline GT-R",
      trim: "R32 2.6 Twin Turbo",
      years: [1989, 1993],
      value: 18000,
      segment: "japan",
      shape: "sport",
      color: "#8ba6a4",
      service: 1.6,
      faultChance: 0.42,
    },
    {
      id: "silvia",
      name: "Nissan Silvia",
      trim: "S13 2.0 K's",
      years: [1991, 1993],
      value: 6200,
      segment: "japan",
      shape: "sport",
      color: "#8ba6a4",
      service: 1.15,
      faultChance: 0.36,
    },
    {
      id: "pulsar",
      name: "Nissan Pulsar GTI-R",
      trim: "N14 2.0 Turbo AWD",
      years: [1991, 1993],
      value: 6800,
      segment: "japan",
      shape: "hatch",
      color: "#8ba6a4",
      service: 1.25,
      faultChance: 0.4,
    },
    {
      id: "240z",
      name: "Datsun 240Z",
      trim: "S30 2.4",
      years: [1971, 1973],
      value: 7500,
      segment: "japan",
      shape: "sport",
      color: "#8ba6a4",
      service: 1.15,
      faultChance: 0.46,
    },
    {
      id: "prelude",
      name: "Honda Prelude",
      trim: "BA4 2.0 Si",
      years: [1988, 1991],
      value: 5000,
      segment: "japan",
      shape: "sport",
      color: "#8ba6a4",
      service: 0.95,
      faultChance: 0.3,
    },
    {
      id: "accord",
      name: "Honda Accord",
      trim: "CB7 2.2 EX",
      years: [1990, 1993],
      value: 4100,
      segment: "japan",
      shape: "sedan",
      color: "#8ba6a4",
      service: 0.8,
      faultChance: 0.26,
    },
    {
      id: "cressida",
      name: "Toyota Cressida",
      trim: "MX83 3.0",
      years: [1989, 1992],
      value: 4400,
      segment: "japan",
      shape: "sedan",
      color: "#8ba6a4",
      service: 0.95,
      faultChance: 0.31,
    },
    {
      id: "starion",
      name: "Mitsubishi Starion",
      trim: "2.6 Turbo",
      years: [1987, 1989],
      value: 5700,
      segment: "japan",
      shape: "sport",
      color: "#8ba6a4",
      service: 1.2,
      faultChance: 0.43,
    },
    {
      id: "eclipse",
      name: "Mitsubishi Eclipse",
      trim: "1G 2.0 GS Turbo",
      years: [1990, 1993],
      value: 5900,
      segment: "japan",
      shape: "sport",
      color: "#8ba6a4",
      service: 1.15,
      faultChance: 0.38,
    },
    {
      id: "swift",
      name: "Suzuki Swift GTi",
      trim: "1.3 Twin Cam",
      years: [1989, 1993],
      value: 2800,
      segment: "japan",
      shape: "hatch",
      color: "#8ba6a4",
      service: 0.7,
      faultChance: 0.28,
    },
    {
      id: "m5",
      name: "BMW M5",
      trim: "E34 3.6",
      years: [1989, 1992],
      value: 16000,
      segment: "europe",
      shape: "sedan",
      color: "#8ba6a4",
      service: 1.5,
      faultChance: 0.35,
    },
    {
      id: "2002",
      name: "BMW 2002 tii",
      trim: "2.0",
      years: [1972, 1974],
      value: 7400,
      segment: "europe",
      shape: "sedan",
      color: "#8ba6a4",
      service: 1.1,
      faultChance: 0.45,
    },
    {
      id: "mgb",
      name: "MG MGB",
      trim: "1.8 Roadster",
      years: [1970, 1973],
      value: 5600,
      segment: "europe",
      shape: "roadster",
      color: "#8ba6a4",
      service: 0.95,
      faultChance: 0.48,
    },
    {
      id: "spider",
      name: "Alfa Romeo Spider",
      trim: "2.0 Veloce",
      years: [1986, 1989],
      value: 7200,
      segment: "europe",
      shape: "roadster",
      color: "#8ba6a4",
      service: 1.1,
      faultChance: 0.43,
    },
    {
      id: "328",
      name: "Ferrari 328 GTS",
      trim: "3.2 V8 Targa",
      years: [1986, 1989],
      value: 55000,
      segment: "europe",
      shape: "sport",
      color: "#8ba6a4",
      service: 2.2,
      faultChance: 0.38,
    },
    {
      id: "countach",
      name: "Lamborghini Countach",
      trim: "5000 Quattrovalvole",
      years: [1986, 1988],
      value: 70000,
      segment: "europe",
      shape: "sport",
      color: "#8ba6a4",
      service: 2.6,
      faultChance: 0.46,
    },
    {
      id: "delta",
      name: "Lancia Delta Integrale",
      trim: "HF 2.0 8V",
      years: [1988, 1989],
      value: 9800,
      segment: "europe",
      shape: "hatch",
      color: "#8ba6a4",
      service: 1.3,
      faultChance: 0.42,
    },
    {
      id: "saab",
      name: "Saab 900 Turbo",
      trim: "2.0 16V",
      years: [1986, 1993],
      value: 5200,
      segment: "europe",
      shape: "hatch",
      color: "#8ba6a4",
      service: 1.05,
      faultChance: 0.3,
    },
    {
      id: "renault5",
      name: "Renault 5 GT Turbo",
      trim: "1.4 Turbo",
      years: [1986, 1991],
      value: 3900,
      segment: "europe",
      shape: "hatch",
      color: "#8ba6a4",
      service: 0.9,
      faultChance: 0.38,
    },
    {
      id: "xjs",
      name: "Jaguar XJS",
      trim: "5.3 V12 Coupe",
      years: [1988, 1991],
      value: 12000,
      segment: "europe",
      shape: "sport",
      color: "#8ba6a4",
      service: 1.7,
      faultChance: 0.47,
    },
    {
      id: "thunderbird",
      name: "Ford Thunderbird",
      trim: "3.8 Super Coupe",
      years: [1989, 1993],
      value: 6700,
      segment: "america",
      shape: "sport",
      color: "#8ba6a4",
      service: 1.1,
      faultChance: 0.37,
    },
    {
      id: "escort",
      name: "Ford Escort GT",
      trim: "1.8",
      years: [1991, 1993],
      value: 3300,
      segment: "america",
      shape: "hatch",
      color: "#8ba6a4",
      service: 0.75,
      faultChance: 0.3,
    },
    {
      id: "s10",
      name: "Chevrolet S-10",
      trim: "4.3 Regular Cab",
      years: [1988, 1993],
      value: 3500,
      segment: "america",
      shape: "pickup",
      color: "#8ba6a4",
      service: 0.9,
      faultChance: 0.33,
    },
    {
      id: "caprice",
      name: "Chevrolet Caprice",
      trim: "5.0 Classic",
      years: [1991, 1993],
      value: 4500,
      segment: "america",
      shape: "sedan",
      color: "#8ba6a4",
      service: 1,
      faultChance: 0.34,
    },
    {
      id: "chevelle",
      name: "Chevrolet Chevelle",
      trim: "SS Coupe",
      years: [1970, 1972],
      value: 10500,
      segment: "america",
      shape: "sport",
      color: "#8ba6a4",
      service: 1.1,
      faultChance: 0.46,
    },
    {
      id: "charger",
      name: "Dodge Charger",
      trim: "V8 Coupe",
      years: [1968, 1970],
      value: 11500,
      segment: "america",
      shape: "sport",
      color: "#8ba6a4",
      service: 1.2,
      faultChance: 0.47,
    },
    {
      id: "daytona",
      name: "Dodge Daytona",
      trim: "2.2 Shelby Turbo",
      years: [1988, 1991],
      value: 4600,
      segment: "america",
      shape: "sport",
      color: "#8ba6a4",
      service: 1,
      faultChance: 0.38,
    },
    {
      id: "barracuda",
      name: "Plymouth Barracuda",
      trim: "V8 Coupe",
      years: [1970, 1974],
      value: 10800,
      segment: "america",
      shape: "sport",
      color: "#8ba6a4",
      service: 1.1,
      faultChance: 0.45,
    },
    {
      id: "fiero",
      name: "Pontiac Fiero",
      trim: "GT 2.8 V6",
      years: [1986, 1988],
      value: 4300,
      segment: "america",
      shape: "sport",
      color: "#8ba6a4",
      service: 1.1,
      faultChance: 0.41,
    },
    {
      id: "cutlass",
      name: "Oldsmobile Cutlass Supreme",
      trim: "G-body 5.0 Coupe",
      years: [1985, 1987],
      value: 3700,
      segment: "america",
      shape: "sport",
      color: "#8ba6a4",
      service: 0.95,
      faultChance: 0.35,
    },
  ],
);
NG.extraSprites = {
  skyline: {
    frame: 0,
    sheet: "cars-v06-japan.png",
    drop: -4.2,
  },
  silvia: {
    frame: 1,
    sheet: "cars-v06-japan.png",
    drop: -3.7,
  },
  pulsar: {
    frame: 2,
    sheet: "cars-v06-japan.png",
    drop: -5.7,
  },
  "240z": {
    frame: 3,
    sheet: "cars-v06-japan.png",
    drop: -5.7,
  },
  prelude: {
    frame: 4,
    sheet: "cars-v06-japan.png",
    drop: -4.9,
  },
  accord: {
    frame: 5,
    sheet: "cars-v06-japan.png",
    drop: 13.9,
  },
  cressida: {
    frame: 6,
    sheet: "cars-v06-japan.png",
    drop: 13.9,
  },
  starion: {
    frame: 7,
    sheet: "cars-v06-japan.png",
    drop: 12.9,
  },
  eclipse: {
    frame: 8,
    sheet: "cars-v06-japan.png",
    drop: 13.2,
  },
  swift: {
    frame: 9,
    sheet: "cars-v06-japan.png",
    drop: 13.7,
  },
  m5: {
    frame: 0,
    sheet: "cars-v06-europe.png",
    drop: -7.5,
  },
  2002: {
    frame: 1,
    sheet: "cars-v06-europe.png",
    drop: -5.7,
  },
  mgb: {
    frame: 2,
    sheet: "cars-v06-europe.png",
    drop: -6.5,
  },
  spider: {
    frame: 3,
    sheet: "cars-v06-europe.png",
    drop: -6.2,
  },
  328: {
    frame: 4,
    sheet: "cars-v06-europe.png",
    drop: -5.4,
  },
  countach: {
    frame: 5,
    sheet: "cars-v06-europe.png",
    drop: 11.2,
  },
  delta: {
    frame: 6,
    sheet: "cars-v06-europe.png",
    drop: 11.4,
  },
  saab: {
    frame: 7,
    sheet: "cars-v06-europe.png",
    drop: 10.6,
  },
  renault5: {
    frame: 8,
    sheet: "cars-v06-europe.png",
    drop: 10.9,
  },
  xjs: {
    frame: 9,
    sheet: "cars-v06-europe.png",
    drop: 12.2,
  },
  thunderbird: {
    frame: 0,
    sheet: "cars-v06-america.png",
    drop: -7.7,
  },
  escort: {
    frame: 1,
    sheet: "cars-v06-america.png",
    drop: -7.7,
  },
  s10: {
    frame: 2,
    sheet: "cars-v06-america.png",
    drop: -8.7,
  },
  caprice: {
    frame: 3,
    sheet: "cars-v06-america.png",
    drop: -7.7,
  },
  chevelle: {
    frame: 4,
    sheet: "cars-v06-america.png",
    drop: -7.7,
  },
  charger: {
    frame: 5,
    sheet: "cars-v06-america.png",
    drop: 8.1,
  },
  daytona: {
    frame: 6,
    sheet: "cars-v06-america.png",
    drop: 8.9,
  },
  barracuda: {
    frame: 7,
    sheet: "cars-v06-america.png",
    drop: 8.1,
  },
  fiero: {
    frame: 8,
    sheet: "cars-v06-america.png",
    drop: 7.9,
  },
  cutlass: {
    frame: 9,
    sheet: "cars-v06-america.png",
    drop: 6.9,
  },
};

NG.extraSprites.delta = { sheet: "car-delta-isolated.png", frame: 0, drop: 0 };
NG.extraSprites.saab = { sheet: "car-saab-isolated.png", frame: 0, drop: 0 };
